module.exports = [
  {   
    Reviewer_email: 'hhw@gmail.com',
    Reviewee_id: 3,
    Rating: 4,
  },
  {   
    Reviewer_email: 'joesmith@gmail.com',
    Reviewee_id: 3,
    Rating: 2,
  },
  {   
    Reviewer_email: 'alicenam@gmail.com',
    Reviewee_id: 3,
    Rating: 5,
  },
  {
    "Reviewer_email": "ebonwick0@umn.edu",
    "Reviewee_id": 3,
    "Rating": 1
  }, {
    "Reviewer_email": "nkinghorne1@smugmug.com",
    "Reviewee_id": 2,
    "Rating": 1
  }, {
    "Reviewer_email": "sbagger2@tamu.edu",
    "Reviewee_id": 2,
    "Rating": 1
  }, {
    "Reviewer_email": "kdambrosio3@columbia.edu",
    "Reviewee_id": 3,
    "Rating": 1
  }, {
    "Reviewer_email": "dkelland4@google.co.jp",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "lbrackenbury5@nationalgeographic.com",
    "Reviewee_id": 3,
    "Rating": 4
  }, {
    "Reviewer_email": "mmarland6@answers.com",
    "Reviewee_id": 2,
    "Rating": 4
  }, {
    "Reviewer_email": "jgilli7@ebay.com",
    "Reviewee_id": 2,
    "Rating": 2
  }, {
    "Reviewer_email": "cmcleary8@admin.ch",
    "Reviewee_id": 3,
    "Rating": 2
  }, {
    "Reviewer_email": "apeplay9@techcrunch.com",
    "Reviewee_id": 3,
    "Rating": 4
  }, {
    "Reviewer_email": "aliebermanna@google.co.jp",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "mboytonb@google.com.hk",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "alightbownc@state.gov",
    "Reviewee_id": 1,
    "Rating": 4
  }, {
    "Reviewer_email": "rcapenerd@time.com",
    "Reviewee_id": 3,
    "Rating": 2
  }, {
    "Reviewer_email": "mverchambree@miitbeian.gov.cn",
    "Reviewee_id": 3,
    "Rating": 5
  }, {
    "Reviewer_email": "selfleetf@cisco.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "pfisbeyg@freewebs.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "lsnowdenh@auda.org.au",
    "Reviewee_id": 2,
    "Rating": 2
  }, {
    "Reviewer_email": "gdeschleini@surveymonkey.com",
    "Reviewee_id": 1,
    "Rating": 4
  }, {
    "Reviewer_email": "jecclestonej@lulu.com",
    "Reviewee_id": 2,
    "Rating": 1
  }, {
    "Reviewer_email": "gpitkaithlyk@arizona.edu",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "sbathal@devhub.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "cchealesm@imgur.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "gsalzburgern@csmonitor.com",
    "Reviewee_id": 1,
    "Rating": 2
  }, {
    "Reviewer_email": "ktallowo@hatena.ne.jp",
    "Reviewee_id": 1,
    "Rating": 2
  }, {
    "Reviewer_email": "efeldonp@cloudflare.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "tpetlyuraq@shutterfly.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "ahanhardr@hao123.com",
    "Reviewee_id": 2,
    "Rating": 1
  }, {
    "Reviewer_email": "cabisettis@fda.gov",
    "Reviewee_id": 1,
    "Rating": 4
  }, {
    "Reviewer_email": "mquennellt@vk.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "alavrinovu@utexas.edu",
    "Reviewee_id": 3,
    "Rating": 3
  }, {
    "Reviewer_email": "slesleyv@si.edu",
    "Reviewee_id": 3,
    "Rating": 1
  }, {
    "Reviewer_email": "jduguidw@people.com.cn",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "eyureninx@hc360.com",
    "Reviewee_id": 1,
    "Rating": 4
  }, {
    "Reviewer_email": "fhunny@github.io",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "rskettz@amazon.co.uk",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "aromaines10@wikimedia.org",
    "Reviewee_id": 2,
    "Rating": 3
  }, {
    "Reviewer_email": "hblackshaw11@fda.gov",
    "Reviewee_id": 2,
    "Rating": 2
  }, {
    "Reviewer_email": "hyewman12@wikimedia.org",
    "Reviewee_id": 1,
    "Rating": 1
  }, {
    "Reviewer_email": "nmeade13@state.gov",
    "Reviewee_id": 3,
    "Rating": 3
  }, {
    "Reviewer_email": "rpighills14@artisteer.com",
    "Reviewee_id": 2,
    "Rating": 2
  }, {
    "Reviewer_email": "sbuddles15@shareasale.com",
    "Reviewee_id": 2,
    "Rating": 3
  }, {
    "Reviewer_email": "gkeuning16@jugem.jp",
    "Reviewee_id": 3,
    "Rating": 2
  }, {
    "Reviewer_email": "codoherty17@yellowbook.com",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "fbalnaves18@flavors.me",
    "Reviewee_id": 2,
    "Rating": 3
  }, {
    "Reviewer_email": "lglazzard19@upenn.edu",
    "Reviewee_id": 1,
    "Rating": 2
  }, {
    "Reviewer_email": "dguy1a@yahoo.co.jp",
    "Reviewee_id": 2,
    "Rating": 3
  }, {
    "Reviewer_email": "mgarfath1b@ucoz.ru",
    "Reviewee_id": 3,
    "Rating": 3
  }, {
    "Reviewer_email": "kvasilchikov1c@seesaa.net",
    "Reviewee_id": 2,
    "Rating": 4
  }, {
    "Reviewer_email": "meverall1d@last.fm",
    "Reviewee_id": 3,
    "Rating": 4
  }, {
    "Reviewer_email": "klukash1e@nature.com",
    "Reviewee_id": 3,
    "Rating": 2
  }, {
    "Reviewer_email": "jcracknall1f@ed.gov",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "mfellows1g@hud.gov",
    "Reviewee_id": 2,
    "Rating": 1
  }, {
    "Reviewer_email": "opadula1h@house.gov",
    "Reviewee_id": 1,
    "Rating": 2
  }, {
    "Reviewer_email": "emaccheyne1i@kickstarter.com",
    "Reviewee_id": 2,
    "Rating": 1
  }, {
    "Reviewer_email": "fehrat1j@senate.gov",
    "Reviewee_id": 1,
    "Rating": 1
  }, {
    "Reviewer_email": "ihirche1k@howstuffworks.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "sdugall1l@yahoo.co.jp",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "dvivyan1m@bloomberg.com",
    "Reviewee_id": 3,
    "Rating": 1
  }, {
    "Reviewer_email": "askoyles1n@livejournal.com",
    "Reviewee_id": 1,
    "Rating": 5
  }, {
    "Reviewer_email": "lcottem1o@tamu.edu",
    "Reviewee_id": 3,
    "Rating": 3
  }, {
    "Reviewer_email": "jjirieck1p@pinterest.com",
    "Reviewee_id": 1,
    "Rating": 1
  }, {
    "Reviewer_email": "sscrammage1q@shareasale.com",
    "Reviewee_id": 2,
    "Rating": 3
  }, {
    "Reviewer_email": "rgiggs1r@gov.uk",
    "Reviewee_id": 2,
    "Rating": 3
  }, {
    "Reviewer_email": "ataplin1s@fema.gov",
    "Reviewee_id": 2,
    "Rating": 4
  }, {
    "Reviewer_email": "lbysouth1t@craigslist.org",
    "Reviewee_id": 2,
    "Rating": 4
  }, {
    "Reviewer_email": "fcraythorn1u@tinyurl.com",
    "Reviewee_id": 2,
    "Rating": 5
  }, {
    "Reviewer_email": "aseefus1v@taobao.com",
    "Reviewee_id": 3,
    "Rating": 2
  }, {
    "Reviewer_email": "nsarfas1w@earthlink.net",
    "Reviewee_id": 1,
    "Rating": 2
  }, {
    "Reviewer_email": "lcardinale1x@ftc.gov",
    "Reviewee_id": 3,
    "Rating": 1
  }, {
    "Reviewer_email": "elount1y@cdc.gov",
    "Reviewee_id": 2,
    "Rating": 5
  }, {
    "Reviewer_email": "tkeedy1z@smugmug.com",
    "Reviewee_id": 3,
    "Rating": 5
  }, {
    "Reviewer_email": "hmccathay20@baidu.com",
    "Reviewee_id": 2,
    "Rating": 3
  }, {
    "Reviewer_email": "kgooms21@eventbrite.com",
    "Reviewee_id": 1,
    "Rating": 1
  }, {
    "Reviewer_email": "fstummeyer22@goo.gl",
    "Reviewee_id": 2,
    "Rating": 1
  }, {
    "Reviewer_email": "mstolz23@vkontakte.ru",
    "Reviewee_id": 3,
    "Rating": 1
  }, {
    "Reviewer_email": "hledwich24@wix.com",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "ttreher25@wikispaces.com",
    "Reviewee_id": 2,
    "Rating": 5
  }, {
    "Reviewer_email": "ltrail26@blinklist.com",
    "Reviewee_id": 2,
    "Rating": 2
  }, {
    "Reviewer_email": "jpegg27@ycombinator.com",
    "Reviewee_id": 1,
    "Rating": 2
  }, {
    "Reviewer_email": "awillshear28@deliciousdays.com",
    "Reviewee_id": 3,
    "Rating": 2
  }, {
    "Reviewer_email": "revetts29@myspace.com",
    "Reviewee_id": 2,
    "Rating": 3
  }, {
    "Reviewer_email": "kboards2a@reverbnation.com",
    "Reviewee_id": 3,
    "Rating": 4
  }, {
    "Reviewer_email": "mkerin2b@stanford.edu",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "mrings2c@salon.com",
    "Reviewee_id": 3,
    "Rating": 5
  }, {
    "Reviewer_email": "bmanderson2d@reuters.com",
    "Reviewee_id": 2,
    "Rating": 2
  }, {
    "Reviewer_email": "rweatherell2e@berkeley.edu",
    "Reviewee_id": 2,
    "Rating": 1
  }, {
    "Reviewer_email": "mcamock2f@wisc.edu",
    "Reviewee_id": 1,
    "Rating": 2
  }, {
    "Reviewer_email": "fcadman2g@geocities.com",
    "Reviewee_id": 3,
    "Rating": 5
  }, {
    "Reviewer_email": "jrake2h@army.mil",
    "Reviewee_id": 2,
    "Rating": 5
  }, {
    "Reviewer_email": "gwilles2i@amazon.co.jp",
    "Reviewee_id": 2,
    "Rating": 5
  }, {
    "Reviewer_email": "wyonge2j@uiuc.edu",
    "Reviewee_id": 1,
    "Rating": 3
  }, {
    "Reviewer_email": "scrighton2k@foxnews.com",
    "Reviewee_id": 3,
    "Rating": 3
  }, {
    "Reviewer_email": "lbellefant2l@sogou.com",
    "Reviewee_id": 3,
    "Rating": 5
  }, {
    "Reviewer_email": "lpeschka2m@baidu.com",
    "Reviewee_id": 2,
    "Rating": 2
  }, {
    "Reviewer_email": "averbruggen2n@constantcontact.com",
    "Reviewee_id": 2,
    "Rating": 4
  }, {
    "Reviewer_email": "drobe2o@over-blog.com",
    "Reviewee_id": 3,
    "Rating": 3
  }, {
    "Reviewer_email": "ghakonsson2p@google.ca",
    "Reviewee_id": 2,
    "Rating": 4
  }, {
    "Reviewer_email": "grichardot2q@salon.com",
    "Reviewee_id": 3,
    "Rating": 3
  }, {
    "Reviewer_email": "bbaugh2r@columbia.edu",
    "Reviewee_id": 2,
    "Rating": 2
  }
];